"""Add regions

Revision ID: 7dfdde156626
Revises: e1461dc09cfb
Create Date: 2022-11-22 12:51:04.881496

"""
from alembic import op
import sqlalchemy as sa
from extract_regions_script import add_regions

# revision identifiers, used by Alembic.
revision = '7dfdde156626'
down_revision = 'e1461dc09cfb'
branch_labels = None
depends_on = None


def upgrade():
    add_regions()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
