"""Add constraints

Revision ID: b5767183598c
Revises: 65052cbc3533
Create Date: 2022-11-22 12:46:22.992821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5767183598c'
down_revision = '65052cbc3533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_comment_comment_id'), 'comment', ['comment_id'])
    op.create_unique_constraint(op.f('uq_language_language_id'), 'language', ['language_id'])
    op.create_unique_constraint(op.f('uq_option_option_id'), 'option', ['option_id'])
    op.create_unique_constraint(op.f('uq_poll_poll_id'), 'poll', ['poll_id'])
    op.create_unique_constraint(op.f('uq_polloption_polloption_id'), 'polloption', ['polloption_id'])
    op.create_unique_constraint(op.f('uq_pollsentiment_pollsentiment_id'), 'pollsentiment', ['pollsentiment_id'])
    op.create_unique_constraint(op.f('uq_polltopic_polltopic_id'), 'polltopic', ['polltopic_id'])
    op.create_unique_constraint(op.f('uq_shift_shift_id'), 'shift', ['shift_id'])
    op.create_unique_constraint(op.f('uq_user_user_id'), 'user', ['user_id'])
    op.create_unique_constraint(op.f('uq_vote_vote_id'), 'vote', ['vote_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_vote_vote_id'), 'vote', type_='unique')
    op.drop_constraint(op.f('uq_user_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_shift_shift_id'), 'shift', type_='unique')
    op.drop_constraint(op.f('uq_polltopic_polltopic_id'), 'polltopic', type_='unique')
    op.drop_constraint(op.f('uq_pollsentiment_pollsentiment_id'), 'pollsentiment', type_='unique')
    op.drop_constraint(op.f('uq_polloption_polloption_id'), 'polloption', type_='unique')
    op.drop_constraint(op.f('uq_poll_poll_id'), 'poll', type_='unique')
    op.drop_constraint(op.f('uq_option_option_id'), 'option', type_='unique')
    op.drop_constraint(op.f('uq_language_language_id'), 'language', type_='unique')
    op.drop_constraint(op.f('uq_comment_comment_id'), 'comment', type_='unique')
    # ### end Alembic commands ###
