"""Add En, Fr languages

Revision ID: d1617badd645
Revises: 7dfdde156626
Create Date: 2022-11-22 20:03:37.036859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1617badd645'
down_revision = '7dfdde156626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
